name: 'Release'

inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  NPM_TOKEN:
    description: 'NPM Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Release'
      id: release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: |
        pnpm run semantic-release
