name: 'Release'

inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  NPM_TOKEN:
    description: 'NPM Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Release'
      id: release
      uses: changesets/action@v1
      with:
        version: pnpm run ci:version
        commit: 'chore: update versions'
        title: 'chore: update versions'
        publish: pnpm run ci:release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}

