name: 'Init'

runs:
  using: 'composite'
  steps:
    - name: 'setup pnpm'
      id: pnpm-setup
      uses: pnpm/action-setup@v2.2.3
      with:
        version: 7

    - name: 'install Node'
      id: node-setup
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: 16
